### ISSUE TITLE
drawRoundedRect not rendering fills correctly

### ISSUE THREAD

**Issue by whizzkid** [GoodBoyDigital/pixi.js#1209]
I discovered that drawRoundedRect does not render properly 

(hijacked @NikkiKoole pixi.js url :)

http://jsfiddle.net/e20cvwr7/6/
the big rectangle has the same fill as the smaller one.
when the big rectangles height is < 430, then it renders the fill.
when it is 430 or higher, then there's no fill.

**Comment by pahund** [comment]
I am using the latest version (2.2.3) and encountered the same issue. Thanks @Cristy94 for the hack you suggested, I'll try that out.

**Comment by BossLevel** [comment]
I am also encountering this issue with 2.2.5 although sadly the above fix doesn't appear to address the issue this time - triangles is set to null.  FYI recPoints for a simple filled roundedRect is an array of length 170 which seems a little excessive although I have no idea as to expected behaviour.  

Let me know what other info I can provide.  

FYI have had to revert to using a plain drawRect call in the mean time.

**Comment by GoodBoyDigital** [comment]
this should work now in v3 in the dev branch. Using @Cristy94's temp fix for now. Cheers all! :+1:

**Comment by pahund** [comment]
Cool, thanks!

**Comment by BossLevel** [comment]
Ta
