### ISSUE TITLE
Pixi v3.0.0

### ISSUE THREAD

**Issue by englercj** [GoodBoyDigital/pixi.js#1296]
### Current Status

**Total Rewrite Progress:** 100% complete

**Reminders for myself:**
- PolyK should be replaced, it has a few bugs ([earcut](https://github.com/mapbox/earcut)?)

# Proposal

## Introduction

Hello all, I decided to write this up to inform the community what I am working on and to gather some feedback. The biggest thing to realize about what follows is that I am working on it right now, and that it is no longer theoretical. Also, keep in mind this has not yet be "blessed" by the rest of the Pixi team so this may not make it in, I am just looking for feedback from the team and the community.

You can watch the work being done in a branch on my fork: https://github.com/englercj/pixi.js/tree/dev-rewrite

If you read this proposal and want to help, fork my branch and submit PRs to the `dev-rewrite` branch and lets get this done!

That being said, v3.0.0 will be a rewrite of PIXI. I have it split into distinct phases with clear goals to accomplish a clean, modular library that will make it easier for us to maintain and for others to contribute.

### Phase 0 - Cleanup/Meta
**Status**: Completed

Phase 0 is to cleanup the code repository, removing things that shouldn't be in the main repo. For example: `examples/`, `docs/`, `trim/`. Each of those should be separate and maintained on their own. It also converts the project to use gulp, reorganizes the tasks for the project, and generally prepare the project for the coming rewrite.

### Phase 1 - Code Modularization
**Status**: Completed
**Related issues**: #307

Phase one is to convert the codebase to use browserify, remove dead code, convert yuidoc to jsdoc comments, and cleanup some style inconsistencies. This is perhaps the most time consuming phase because it requires combing through every source file in pixi and changing a lot. This phase will make it much easier to refactor the library and accomplish later phases.

### Phase 2 - Component Modularization
**Status**: Completed

Once the library has been revamped from a code-quality standpoint the next step is to remove circular dependencies and split the core library into multiple discrete modules. Each module will be in a separate folder within the `src/` directory of the project, but should be split into separate repos at a later date.

The modules I have in mind are:
- `core` - Core renedering and display (math, DO, DOC, Sprite, SpriteBatch, Graphics, textures, renderers).
- `spine` - Adds spine support.
- `loader` - Adds loaders for the different things pixi supports.
- `filters` - Adds a pack of different filters.
- `text` - Adds text support.
- `extras` - Adds TilingSprite, and MovieClip support (could use a better name).
- `interaction` - Adds user interaction support.

### Phase 3 - Decoupling and API Normalization
**Status**: Completed

At this point the project has been split into multiple "modules" within the repo, but are still interdependent on each other. That is, even though the code is separated you couldn't have a custom build that leaves out pieces because they are too tightly coupled. This phase is to decouple modules from each other and let them be standalone. Core should work fine on its own, and other modules should just extend core and add support. There are also leaky functions and a lot of dependence on global state, that should also be removed in this stage.

This phase also includes modifying strange inconsistencies in the API to unify it a bit. For example, sprites have properties for filters/masks but to set the texture you use a method. Fixing some of these evolution in the code will result in easier integration and maintenance.

### Phase 4 - Prefer dependencies and create custom builds
**Status**: Complete
**Related issues**: #1283

Now that modules exist, and are decoupled, we can create custom builds that include only subsets of the pixi functionality that users can tailor to their needs. This phase will also take this opportunity to try and refactor out custom code in favor of more mature modules in the npm ecosystem.

Some modules we can start using (thanks @mattdesl):

- [point-in-polygon](https://www.npmjs.com/package/point-in-polygon), [gl-vec2](https://www.npmjs.com/package/gl-vec2), [point-circle-collision](https://www.npmjs.com/package/point-circle-collision), [gl-mat4](https://www.npmjs.com/package/gl-mat4) for `geom` package
- [polyline-normals](https://www.npmjs.com/package/polyline-normals), [bezier](https://www.npmjs.com/package/bezier), [adaptive-bezier-curve](https://www.npmjs.com/package/adaptive-bezier-curve), [arc-to](https://www.npmjs.com/package/arc-to) for 2D graphics
- [glslify](https://www.npmjs.com/package/glslify) or [brfs](https://www.npmjs.com/package/brfs) for managing shader code 
- [mouse-position](https://www.npmjs.com/package/mouse-position), [scroll-speed](https://www.npmjs.com/package/scroll-speed), [mouse-event-offset](https://www.npmjs.com/package/mouse-event-offset), [wheel](https://www.npmjs.com/package/wheel) for interaction
- [img](https://github.com/npm-dom/img), [events](https://www.npmjs.com/package/events), [webgl-context](https://www.npmjs.com/package/webgl-context), [prefix-style](https://www.npmjs.com/package/prefix-style), [texcoord](https://www.npmjs.com/package/texcoord), [gl-shader-errors](https://www.npmjs.com/package/gl-shader-errors), etc.

### Phase 5 - Rewrite Interaction Manager
**Status**: Completed
**Related issues**: #241, #325, #346, #785, #950, #1096, #1252, #1291

There are a lot of issues related to the interaction manager and how it works, this phase will be a rewrite of this module so clear up some of the issues people have been reporting. Hopefully when this is done we will have a clearer interaction manager along with DOM-like bubbling, and real events (instead of raw callbacks).

### Phase 6 - Rewrite Asset Loader
**Status**: Completed
**Related issues**: #312, #387, #776, #1290 

The loader has evolved a lot over time, and some of the older components got left behind. The API for it is a little hap-hazard and awkward. This rewrite should address the issues the community has with this module, increase performance, and make it easier to maintain.

There is also still a coupling of the core code to the texture caches used by the loaders. This phase should remove that.

### Phase 7 - Rewrite Stage
**Status**: Completed
**Related issues**: #1232, #1264, #1285

There is a lot of confusion over what `Stage` is and why it exists. Many people have asked "why can't I pass any DOC and have it rendered?" This phase will be to implement that functionality and remove the stage from the library.

### Phase 8 - Optimization/Cleanup Pass
**Status**: Complete
**Related issues**: #1097, #1238, #1260

There are a couple hot functions that could use an optimization pass. Lots of temporary variables and other things that cause GC churn that need to be fixed. This phase is to clean up those parts and help make pixi as clear and effective as possible.

I also want to cleanup some long standing issues in this phase, that should be pretty simple to solve. Most involve some "messy" code that should be simple to clean up. I will also take this opportunity and go through all the `TODO` comments in the code, and actually do them.

### Phase 9 - Rewrite Examples
**Status**: Complete

The examples have a ton of code duplication, and no framework for actually creating them making it tedious if not difficult to add more examples. In the new examples repo there should be a framework for easily creating new examples using a handlebars/assemble/gulp build process. Code can then be shared via browserify.

### Completion

After these phases I feel that pixi will be in a good state to be extensible and maintainable by the community. If you have feedback, or questions I'd be happy to try and answer them here. This effort should go towards fixing 20+ issues in the list and make it much easier for other developers to jump into the code and fix issues on their own in the future.

**Comment by englercj** [comment]
> Will using browsefy modules still build a PIXI object that can be used the same way people currently use pixi?

Nothing changes for users that use pixi in the way they use it now, the final built file works the same way. All it does it let other browserify users and node users have easier access, and we get access to npm modules, and the code is much cleaner.

> My brain is a little concerned about phase 4 as integrating other modules as it seems like it could add layers to pixi that may not be required. But thats something we can talk about when we ya get to phase 4 :)

Not sure what you mean, this doesn't add code, it removes it. It is removing layers from pixi so that there is less code to maintain and create custom. Instead we use mature modules that are well tested and therefore reduce our complexity and bugs significantly.

I think that this is one of the most important parts of this, because pixi has a *lot* of bugs because we reinvent the wheel so much.

**Comment by GoodBoyDigital** [comment]
Nice nice! I disagree with your last comment though - reinventing the wheel (to a certain degree) is what made pixi what it is and how we manage to get such good performance so far. It also lets us try new ways of doing things which is very important to me. 

I know this is down to personal taste, but I'm not really a fan of the tiny little modules that pop up on npm. I want to make sure that pixi does not become a collection of fragmented code that requires a bunch of tiny little modules that more often than not could simply be a function.

That said I will certainly keep an open mind about what your are saying and as we come to that part we can discuss it.

I agree that structurally its evolved and is in need of a tidy. Pixi is very important to me (as it is to you) and I just want to be VERY careful with these big proposed changes. 

Cheers!

**Comment by drkibitz** [comment]
@englercj I kind of disagree with that last comment too, for a different reason. I do not think reinventing the wheel is the reason there are bugs, but it does contribute to them popping up.

**Comment by photonstorm** [comment]
I think before any of this is even started you should all try and answer a fundamental, yet basic question first: *What do you actually want Pixi to be?*

Although billed as a 'renderer' I think everyone here can agree it never really was just that, even from the start. It has clearly evolved as a result of how @GoodBoyDigital needed to use it on a day-to-day basis internally in their client work. This is obvious from the way features were added that it grew based on  what could be deemed a 'client led' roadmap. This isn't a bad thing necessarily, but as the popularity of Pixi grew it bought into question why some of those choices were made.

With a project like this I think it's fair to say that its structure is a direct result of the workflow that goes on within the GoodboyDigital team, who are arguably the most important Pixi user of all. If browserify was a core tool they used internally then I have no doubt you'd see Pixi using it already, but it clearly isn't. The moment they start questioning if it should be used is the moment the project will loose momentum and start mothballing.

Pixi development isn't a purely altruistic endeavour. It has to either remain a vital core part of Goodboys day to day workflow, or be so open and well adopted that the wider community can and will carry out all development instead. I believe this is a fine line.

Assuming a rewrite in this manner will suddenly open the flood-gates to developers who wouldn't otherwise have helped is wishful thinking at best. I believe the reality is that there's a very finite number of developers who have the technical ability to help anyway. If Mat were to spend time writing in detail how Pixi works, explaining about the batch process, the shaders and the rest of the internals then I can't help but think this single act could help bring in more developers in than any other actually. But that's an aside (and really could do with happening regardless)

If Pixi is to truly be a *pure renderer* and nothing else then it needs entirely stripping out and turning into such. From this then perhaps @GoodboyDigital could work Pixi into a new project that adds in all of the extras they actually need for day-to-day work and not even have them as part of the core library (even in module form).

However as Pixi isn't really a renderer at all right now (it's turned into a bit of a swiss army knife!) then maybe this is where the discussion should start off? I think both Mat and Chad (and everyone else!) should agree with a joint definition, which should evolve into a core features list and roadmap, before any code is touched at all.

**Comment by mattdesl** [comment]
@englercj

> After I replace code in pixi with external existing modules, what code is left that is pixi-specific that could become agnostic?

It's hard to say, since so much of Pixi is written with side-effects and thus generally harder to "rip out" into decoupled modules. For example, the ellipse function (using quadratic curves) would be useful in a module, but not in the current way it's written. 

@drkibitz

> The canvas is probably the most simple in that it would be nice to circumvent the need for a canvas in general, and just provide the context directly

Do you mean like passing a CanvasRenderingContext2D to the WebGLRenderer? I would be in favour of this, and I've started doing this in my own tools. When something needs to operate on a webgl/2d canvas, I prefer passing around contexts for a few reasons:

- this way there is only a single (top-level) call to getContext, which ensures the user has exact control over the context attributes (like premultipliedAlpha and failIfMajorPerformanceCaveat)
- some debuggers (like Chrome Dev Tools) have trouble inspecting draw calls when you have multiple getContext calls
- webgl/2d context always has a back-reference to `canvas` if that is needed

On the topic of re-factor, I really think that ThreeJS-style object options in constructors might be worth considering. Especially for WebGLRenderer, which has become annoying with the mix of required/optional parameters. 

@GoodBoyDigital

> My brain is a little concerned about phase 4 as integrating other modules as it seems like it could add layers to pixi that may not be required. 

Small and focused modules will help minimize this problem. If a module is "too big" or doesn't do something quite in line with how Pixi should do it, then it might be a case where a new module can be created. The benefits:

- separation of concerns. e.g. no need to maintain event emitter code inside a rendering framework
- others can utilize (and improve on) the module without bringing in the entire bulk of Pixi
- reduced code duplication in final browser bundle
- the code can be versioned and tested independently of Pixi

--

@photonstorm I agree with your points. Ultimately everything is up to the GoodBoyDigital team since they will be the ones that continue to maintain and improve Pixi. If they don't like the browserify / small modules route then a rewrite of this magnitude would have negative effects on the future of Pixi, and a fork (new project name etc) might be a better approach.

I have stopped using Pixi for personal projects because it does not produce re-usable code, and because it's usually overkill for the work I do. Every day Pixi seems to grow exponentially (in size and complexity), with new features that 99% of the time I will never need. I still use Pixi at work because it's well documented (good for teams / juniors) and because the existing ecosystem of npm modules have not caught up to it. This will probably change in time, as stackgl and similar projects become more mature.

**Comment by drkibitz** [comment]
@mattdesl 

> Do you mean like passing a CanvasRenderingContext2D to the WebGLRenderer?

Yes.

> the code can be versioned and tested independently of Pixi

:+1:

**Comment by GoodBoyDigital** [comment]
Hello all! 

@mattdesl thanks for sharing so much information! That combined with a decent conversation with @englercj has really helped in my understanding of this approach. 

The penny is starting to drop as it where and I'm starting to get a more excited! I still need to see and engage in this new philosophy for me to truly get to grips with it I feel, so im certainly up for giving it a go and seeing where this heads. Just be prepared for some silly questions :) 

Research and playing around for me when I get home i think...

With regards to the things I do understand a lot better.. I'm 100% on board with a solid refactor of certain core parts of pixi that will make it much easier for people to only use the parts of pixi that they need to use rather than rolling it all into one big ball that includes everything. A more DRY approach and following this lovely statement:

"Make modules be standalone, defined as: they don't require extra code for their use-case to be added to core."

After driving a car for 10 hours today I had a lot of thinking time and have a few solid ideas that I am confident will get us to that goal!

I guess my question to you all is what would you consider to be core pixi? would it be as simple as:

webGLRenderer
canvasRenderer
displayObject
displayObjectContainer
Sprite
Graphics

That seems like it would be pretty nice and bare bones to you all?

And a few more thoughts..

-Whats pixi all about?

The two most important things to me for pixi are this:
1 - Its fast and has killer performance
2 - Its has a clean simple API that abstracts away all the complexities of webGL / Canvas rendering so developers of all skill sets can crack on and make the content that visually look killer! Like magic :)

How we ended up where we are..

The focus on pixi so far has always been on the end result and it performing what is required. The requirements have come from either a necessity for a project I'm working on or community feedback from its users. So its has kind of grown fairly organically. This has been a good thing in terms of finding out what pixi is actually useful for!

I am confident that what we have feature wise is strong and to be honest I don't think that there are any left that need to be added to pixi as it is. Certainly some refactoring, making existing features stronger  and moving some out of the core offering.. But not any real new ones!

I do have some higher level ideas but they will certainly be plugins and separate (A 2D dynamic lighting system "pixiLights" being one of them!)

So yup, I honestly think they are the 2 main reasons that the uptake has been so good this year! So with that in mind I think the idea of making pixi leaner and generally more module is a thing that has to happen.

That way more advanced users can pick and choose the elements from pixi that are required for their projects and new comers or people who don't wish to dabble can have the same experience they currently have when using pixi.

win win right?

Also @mattdesl out of curiosity, what are your thoughts on existing engines like three.js?

**Comment by lain-dono** [comment]
>A 2D dynamic lighting system "pixiLights" being one of them!

LightSpriteBatch and stuff from http://www.goodboydigital.com/pixijs/pixilights/? It is not perfect-pixel shadows. Right?

**Comment by mattdesl** [comment]
@GoodBoyDigital

The thing to keep in mind is that the re-write is only a small step toward modularity. Pixi is *never* going to end up as modular as, say, [stackgl](https://github.com/stackgl/bunny-walkthrough/blob/master/index.js). And that's OK, since most people are happy with Pixi as-is. 

At a high level the goal of npm modules would be to: *"use dependencies to make the codebase more manageable."* Examples:

  - using an "events" module instead of baking one into the Pixi codebase
  - instead of copy-pasting chunks of code (like triangulation, `point-in-polygon`, webgl context detection, etc), they should be brought in via a dependency, so we can receive patch updates upstream
  - splitting some of the current agnostic code bits into their own modules (e.g. hex/rgb conversion)


I'm sure the options will become more clear as more work is done on the rewrite/fork.

**Comment by marcusstenbeck** [comment]
I'm trying to figure out how to best contribute to Pixi. At the moment I'm scanning the issue tracker and finding small stuff that'll familiarize myself with the codebase. Eventually I'm going to want to start working on more in-depth issues, so I'd love if @GoodBoyDigital and @englercj could start labeling issues to make it easy to contribute to development rather than bugs. Also, can I help make this happen?

**Comment by englercj** [comment]
@marcusstenbeck You are 100% correct, I used to be on top of labeling everything but as the size of the code and the popularity increased I wasn't able to keep up! With the rewrite there will be new organizational strategies (the extra modules will have their own repo) which means we will better be able to deal with the volume of issues and narrow their scope.

At the same time I'm hoping we can move development to the pixi.js organization to better manage permissions across repos and me/Mat don't necessarily have to solo maintain the entire pixi ecosystem. There are definitely going to be opportunities to help going forward, try to hang in there with us as we figure out the best ways to get everyone involved!

**Comment by mattdesl** [comment]
Also, @GoodBoyDigital, on the topic of Threejs...

I think it's an awesome project that has a much larger scope than Pixi, and also deals with a much more challenging domain (3d graphics). I also think other solutions like Stackgl and Pex are still very far away from it. 

That said, it has the same problems being discussed in the thread. Very hard to write reusable code with threejs (lots of existing plugins do not work after a few versions), and also very hard to pick apart pieces of Threejs to use them outside of its intended scope (like vector math and color utils). It's constantly adding new features, complexity and bloat with no real end in sight, when really those features would be better suited in user land.

**Comment by wojciak** [comment]
This is a very good step forward. I think the project will benefit from it. 
What I'd like to see is de-coulping the core from DOM related methods and make these methods pluggable (getElementsByTagName I'm looking at you :P). This would allow for simple dependency management when building for environment different then the browser (eg. WP8.1, Tizen, CocoonJS).

**Comment by englercj** [comment]
@wojciak That is definately one of our goals, keep in mind the fn you describe is not in what we are considering core for v3.

```
I guess my question to you all is what would you consider to be core pixi? would it be as simple as:

webGLRenderer
canvasRenderer
displayObject
displayObjectContainer
Sprite
Graphics

That seems like it would be pretty nice and bare bones to you all?
```

That is the running idea right now, everything else is a separate module/plugin.

**Comment by wojciak** [comment]
:+1:

**Comment by marcusstenbeck** [comment]
What about current `TODO`s in the code? Outdated, current, or "who knows"?

**Comment by marcusstenbeck** [comment]
👍👌

**Comment by MattMcFarland** [comment]
Hi, new here and just found pixi - I'm excited about this rewrite and plan on watching it closely.  I just wanted to share my 2 cents on improving maintainability, they will be generic but hopefully they will apply in most aspects of this rewrite.

Generally speaking, there are a few things that really help maintainability of projects (from my experience working on enterprise apps)

1. Global Design Patterns (Not graphics design, but syntactic sugar)
What I mean to say is, any development type doc that details coding patterns that should be followed.  Defining object construction patterns, module patterns, JSON patterns help the "knowledge transfer" process and improve longevity / maintainability.

2. Core Framework - A repository of one single module that holds items that are needed by everything else.  THe Core Framework should NOT have anything that is used by SOME of the other modules.

example `pixi/framework/core/`

3. Shared Assets Library - A repository of modules that COULD be considered part of the CORE FRAMEWORK - BUT becuase other modules do not necessarily need them, they should be put here - and can be accessed by any other module, but is only added if needed.

example `pixi/framework/shared/[asset-name]/`

4. Agnostic Modules - Modules that need core framework to run, but do not need any other Agnostic Modules ever, and should be considered completely separate, almost like separate products or applications.  Agnostic modules need core framework, and may use shared assets library or not.

example `pixi/modules/[module-name]/`
Just 2 cents.  I think everything already stated is 100% great and the plan as is great.  Just wanted to share my experience is all.  I would need to have more knowledge of the source code to provide anything more specific.

**Comment by serprex** [comment]
I've been looking into finding an npm module to handle events. I don't believe EventEmitter is what pixi is looking for (no way to signal that an event is handled). There are a few EventTarget npm modules though

**Comment by gre** [comment]
@serprex What about `signals` https://github.com/millermedeiros/js-signals ?

**Comment by englercj** [comment]
@gre Too slow :)

**Comment by kittykatattack** [comment]
If you're planning a massive rewrite, why not future-proof with ES6 modules using SystemJS?

**Comment by englercj** [comment]
@kittykatattack We had that discussion a million times now, the basic gist is:

- We still want a single-file output, so there will still be a build step either way.
- The polyfils for ES6->ES5 produce some pretty gross (unoptimized at times) code.
- ES6 modules do nothing for letting make use of the npm registry.
- Saying that browserify is "not future proof" is just FUD, it isn't going anywhere for a long time.

and many other reasons you can find by searching around the issue list.

**Comment by kittykatattack** [comment]
@englercj Thanks for explaining that

**Comment by mattdesl** [comment]
ES6 is pretty fantastic in some ways; 6to5 produces very clean transpiling for things like arrow function, spread, default params, rest, string templating, classes, etc. It plays fine with modules and npm. :) But it's a different beast, introducing some new complexities for contributors, and brings to question what happens when some es6 code is pulled out of core into its own module.

@gre I've been on both sides of the fence with signals. On large projects signals have some advantages, but more recently I've found events play better with npm/modules as a whole, and also have potential for FRP down the road. The real selling point of events for me is code readability:

```js
var foo = createFoo()

//is this a signal? a boolean? a jQuery-like getter function? 
console.log( foo.started ) 

foo.started.addOnce(handler)
```

Compared to events which does not carry the same ambiguity, and reads almost like regular English. "Once foo is started, do handler."

```js
var foo = createFoo()
foo.once('started', handler)
```

But I admit it mostly comes down to personal preference, since the differences are pretty minor. :)

**Comment by englercj** [comment]
>  It plays fine with modules and npm. :)

You still have to use CJS for npm modules, you can't just do raw ES6 and the node ecosystem suddenly works. Unless I grossly misunderstand something you are talking about compiling the ES6 then publishing that?

**Comment by mattdesl** [comment]
Yeah, but in the case of Pixi we already have a bundle step (browserify) so adding 6to5ify would be pretty transparent to end-users consuming with npm / bower / whatever. It gets a little more complicated when you have separate modules, because those might not need a bundle step (i.e. [point-in-polygon](https://github.com/substack/point-in-polygon) is just raw source).

With that said, I don't really think ES6 is necessary for Pixi.

**Comment by englercj** [comment]
@mattdesl I meant us using npm modules. Even when using browserify we have to include npm modules with `require` using a CJS pattern anyway.

**Comment by mattdesl** [comment]
You can require stuff and still take advantage of es6 features. :)

**Comment by englercj** [comment]
@mattdesl Of course, I just don't think there are many worth us implementing for our use cases.

**Comment by NikkiKoole** [comment]
just bumping this one to say how impressed I am at the rate and work you two @englercj  @GoodBoyDigital  are pumping out in the dev branch.

**Comment by adireddy** [comment]
+1 :+1:

**Comment by ryanmcnz** [comment]
Some wonderful brilliance going down here, thanks for being so awesome guys! @GoodBoyDigital @englercj

**Comment by drkibitz** [comment]
Just had a quick perusal of progress, also very impressed!

Hope it's ok to add 2 (more) ¢, probrably not the last ;)

I notice there are a couple, or few mixins now in existence, e.g. cacheAsBitmap, interactionTarget, eventTarget. I have no issues with this pattern, many times it is perferred, but having quite a bit of experience with react.js, I do like having things organized in such a way that a mixin is easy to spot, either by directory structure, module name, or both. Just a thought.

**Comment by SharpleafCC** [comment]
Will version 3 have a download similar to the way it is now?
Like JUST a Pixi.js file that we'll be able to grab without having to do the whole "build-on-the-command-line" kind of thing?

**Comment by gre** [comment]
I'm not the owner here but I guess that's for sure. and if not, it is very easy to make one.

Keep up the great work guys

**Comment by englercj** [comment]
@SharpleafCC You will never have to build pixi.js yourself if you don't want to. We will *definitely* have a distributable that browserify will build for us.

**Comment by englercj** [comment]
Closing this now since we have completed the scope of this issue.

**Comment by SharpleafCC** [comment]
Does this mean v3 is ready? :D

**Comment by drkibitz** [comment]
:+1: great work!

**Comment by englercj** [comment]
@SharpleafCC No, it means the scope laid out in this issue has completed. The developer preview is out if you want to start working with the new lib, and we should be able to release the official v3 soon.

**Comment by lucasb-eyer** [comment]
Does "developer preview" mean "whatever is currently in the `dev` branch", or is there some other place I'm missing?

**Comment by englercj** [comment]
@lucasb-eyer Developer Preview means "pre-release for developers". The `dev` branch is the latest bleeding edge code, the [releases](https://github.com/GoodBoyDigital/pixi.js/releases) are the latest releases of the library (including pre-releases like our RCs).

**Comment by lucasb-eyer** [comment]
I didn't even know about the github releases page! Thanks for the link and sorry for the noise.
