### ISSUE TITLE
IE 10/11 indexSizeError when unloading image asset and IE tries to render it right after

### ISSUE THREAD

**Issue by JanAmbrozic** [GoodBoyDigital/pixi.js#1331]
There is an existing issue that looks similar to the already closed #614. 

I have a scene switching components that unloads/loads assets depending on the scene but it is using the same pixi object. So for a brief period of time there is a "placeholder" 1x1 image (our asset loader adds that if the loading is not done when the image is trying to be rendered) that is  being rendered for some reason in IE (works in all other desktop/mobile browsers - the image is actually there on time).

I only tested CanvasRendered because IE10 only supports that but the fix should be good for all WebGL as well.

I have a fix for it so I'll add a PR in few minutes.

**Comment by englercj** [comment]
I think this has to do with how you are "unloading" assets as I mentioned in the PR.

**Comment by GoodBoyDigital** [comment]
Pretty sure this is licked in v3. Please let us know if it still persists! thanks :+1:

**Comment by danieldunderfelt** [comment]
Hi there! Sorry to open this issue, but it is still present. We have an app that doesn't work in any IE version because it throws the `IndexSizeError` when it tries to draw an image to a CanvasRenderer on ie 10 and 11. We are running Pixi.js v3.0.11. Here's the code that throws:

```
renderer.context.drawImage(
                texture.baseTexture.source,
                texture.crop.x * resolution,
                texture.crop.y * resolution,
                width * resolution,
                height * resolution,
                dx  * renderer.resolution,
                dy  * renderer.resolution,
                width * renderer.resolution,
                height * renderer.resolution
            );
```

The texture exists, all values are over 0 except `dx` and `dy`. `resolution` is 1.

Is there any way to circumvent this?

**Comment by themoonrat** [comment]
The issue is occuring because the dimensions it's calculating are incorrect. Other browsers just handle it, IE throws an error. For example, if it tries to draw from the source image thinking it's 100x100 pixels, but the source image is actually only 90x90 pixels, that error this thrown. 

Are the resolutions of the assets all 1 as well? I've had the issue when using resolutions like 0.5 for textures / rendering - and I changed that code to do 
```
renderer.context.drawImage(
    texture.baseTexture.source,
    Math.floor(texture._frame.x * resolution),
    Math.floor(texture._frame.y * resolution),
    Math.floor(width * resolution),
    Math.floor(height * resolution),
    Math.floor(dx * renderer.resolution),
    Math.floor(dy * renderer.resolution),
    Math.floor(width * renderer.resolution),
    Math.floor(height * renderer.resolution)
);
```
The rounding down solved the issue, but I've not had time to delve into any potential side effects

**Comment by danieldunderfelt** [comment]
@themoonrat nope, didn't help :/ I don't know which value is wrong, as it just marks the whole function call. I've inspected all values and they seem fine. The resolution is 1.

**Comment by themoonrat** [comment]
set logging to log out each of those values, so 
```
console.log('texture.baseTexture.source.currentSrc: ' + texture.baseTexture.source.currentSrc);
console.log('texture.baseTexture.source.width: ' + texture.baseTexture.source.width);
console.log('texture.baseTexture.source.height: ' + texture.baseTexture.source.height);
console.log('texture.crop.x * resolution: ' + texture.crop.x * resolution);
```
etc. for the drawImage when it goes wrong. Should find something rogue that way

**Comment by danieldunderfelt** [comment]
Yup, `sx` (or `texture.crop.x` from above) was under 0, causing IE to freak out. I did the following:

```
width = x < 0 ? width + x : width
height = y < 0 ? height + y : height
y = y < 0 ? 0 : y
x = x < 0 ? 0 : x
```

If either coord is under 0, I set it to 0 and subtract the value it was from width or height respectively. This is the only way I got it to work. Could Pixi maybe abstract this so it wouldn't be an issue? Chrome handled negative offsets like a champ.

**Comment by themoonrat** [comment]
I'd investigate as to why that value is getting set negative in the first place, as that is definitely not right.

Chrome handles like a champ... but technically IE has a point. It _should_ point out if it's being asked to draw from a texture from a negative point, when pointer 0,0 is the origin.
