### ISSUE TITLE
when page is not cached wrong position

### ISSUE THREAD

**Issue by DennisSnijder** [GoodBoyDigital/pixi.js#1363]
when my page is not cached the positions are messed up

http://dennis-snijder.nl/bomb/

**Edit** (cengler - 2015/20/1): Removed some raw language.

**Comment by englercj** [comment]
Are you using width/height of objects before the texture loads? Are you preloading assets before using them?

**Comment by englercj** [comment]
Looked again and saw you doing this:

```js
pixi.Texture.fromImage('./res/sprites/bom.png');
```

This means that if you use that object before it is loaded and try to set position based on width/height of the sprite, there is no way to know how big that sprite will be because the texture hasn't yet loaded.

Either preload your assets, then use them; or set your sprite positions once the texture has loaded.
