### ISSUE TITLE
Spine: Mixed up images.

### ISSUE THREAD

**Issue by aholla** [GoodBoyDigital/pixi.js#1368]
I have an animation wich has two difference images attached to multiple bones. 

When the animation is loaded into PIXI, the images are attached to the opposite bones.

Using the current pixi.dev.js from the dev branch.

**Comment by aholla** [comment]
Also has this new Spine loader been tested? 

I cant seem to get Spine to export the .atlas file in a json format. Instead it comes out as a text file. I also don't see where PIXI is parsing this text file? I cant see how this works.

This could be why it doesnt know which image to attached to which bone.

The first animation plays fine but when i change animation with "setAnimation" it doesn't display correctly.

**Comment by NathanSweet** [comment]
Spine always exports an atlas in the "libgdx" atlas format, which is a simple line delimited format. The parsing of this happens in spine.js.

Spine can pack any number of images into a single atlas. You aren't required to have an atlas per skeleton.
http://esotericsoftware.com/spine-texture-packer#Packing

Likely pixi.js has its own atlas file format and objects separate from the Spine atlas, so it may be an issue that they don't work together. pixi.js could use its own atlas objects to render Spine animations by implementing an AttachmentLoader rather than using the AtlasAttachmentLoader from spine.js (which uses a Spine atlas).

**Comment by englercj** [comment]
> Likely pixi.js has its own atlas file format and objects separate from the Spine atlas, so it may be an issue that they don't work together.

We support both, our spine loader uses the atlas format. This request is about using a different tool for creating atlases and mapping that back onto the spine objects. This part is likely a pixi bug, but probably not in our loaders or spine parsing but in our runtime.

**Comment by englercj** [comment]
Tracking this at pixijs/pixi-spine#14.
