### ISSUE TITLE
sampler2D uniform in custom shader samples incorrect texture

### ISSUE THREAD

**Issue by activetheory** [GoodBoyDigital/pixi.js#1427]
Hi!

I think I've found a bug, but hopefully I'm just doing this wrong.

I've created a custom shader that extends AbstractShader, and the uniform is a Texture. In the shader, when trying to access that sampler2D, I get the wrong results:

    'void main(void) {',
         '   gl_FragColor = texture2D(otherCat, vTextureCoord);', //this shows the texture from uSampler
        //'  gl_FragColor = texture2D(uSampler, vTextureCoord);', //this is just black
    '}'

The "uSampler" texture is accessed through my new "otherCat" uniform, and "uSampler" itself comes up empty.

Case: http://files.activetheorylab.net/pixi/

Thanks!

**Comment by englercj** [comment]
Looking into this, I think this is because the `uSampler` uniform is optimized out since you are not using it (it is commented) and the uniform position we check for it is then `null` because of that.

That causes issues because in the shader it then binds your custom texture to `gl.TEXTURE0`:

https://github.com/GoodBoyDigital/pixi.js/blob/cfe3447e9213134867c39fc963eb02ed05ba413c/src/pixi/renderers/webgl/shaders/PixiShader.js#L275

Which is hard-coded to be the sprite's texture in a filter:

https://github.com/GoodBoyDigital/pixi.js/blob/cfe3447e9213134867c39fc963eb02ed05ba413c/src/pixi/renderers/webgl/utils/WebGLFilterManager.js#L298-L299

This would probably work if you were using both textures so that the uSampler wasn't optimized out.

**Comment by activetheory** [comment]
Hey,

Thanks so much for the response.

I've tried updating the case to lookup both textures, but the result I'm getting now is instead of mixing two images, it mixes one with black -- essentially just making it 50% transparent.

http://files.activetheorylab.net/pixi/?new

Cheers!

**Comment by englercj** [comment]
Does the same issue happen when you treat it as a filter instead of as a shader for a sprite?

So instead of `sprite.shader = ..;` try `sprite.filters = [..];` I'm curious if it is a problem with the shader code path instead of the filter code path.

**Comment by activetheory** [comment]
`sprite.filters` does work, although the uv's seem to be flipped and a bit off.

http://files.activetheorylab.net/pixi/?filter

**Comment by oal** [comment]
I was bitten by this bug today, too. Setting it as a filter works as expected, but when using it on the shader property, it only ever samples from one of the textures.

**Comment by GoodBoyDigital** [comment]
All fixed up in v3 chaps! :+1:  closing for now..

**Comment by merixstudio** [comment]
Hey, @GoodBoyDigital can you help us backport this fix to v2? Can this be done easily? Any guidance appreciated.
