### ISSUE TITLE
Spine anchoring

### ISSUE THREAD

**Issue by aholla** [GoodBoyDigital/pixi.js#1446]
Can we add spine anchoring?

Currently if I rotate my spine animation it rotates around the center, it would be great to be able to set anchor points.

**Comment by NathanSweet** [comment]
Typically in a Spine runtime the position at which you draw the skeleton maps to 0,0 in world coordinates in Spine. This is the only reference point that makes sense for positioning. Since a skeleton is nearly always animated, it's AABB is constantly changing position, so performing operations on the center of the AABB isn't very helpful.

Depending on your needs, it might be best if you adjust the rotation of a particular bone in your skeleton so you can exactly control the rotation origin.

**Comment by englercj** [comment]
Tracking this at pixijs/pixi-spine#13.
