### ISSUE TITLE
primitive particles - graphics objects or textures?

### ISSUE THREAD

**Issue by mreinstein** [GoodBoyDigital/pixi.js#1451]
I'm working on a project which has a number of particles that are essentially untextured, colored rectangles with alpha transparency. 

I'm wondering what is the best way to represent these in pixi? Should I create a `pixi.Graphics` object and draw all the particles into that? should I create a separate Graphics object for each particle? Or should I use a 1px X 1px textured sprite for each particle?

All the examples I've seen go down the textured sprite route, but given my project uses only colors, alpha transparency, and are rectangular I thought maybe pixi.Graphics might be the way to go.

I realize this may not have a right or wrong answer but I'm just curious about the performance implications of using a ton of graphics objects vs using tons of small textures.

**Comment by englercj** [comment]
> Should I create a pixi.Graphics object and draw all the particles into that?

You could do that.

> should I create a separate Graphics object for each particle?

Never do that.

> Or should I use a 1px X 1px textured sprite for each particle?

Ideally you would use a single texture for all the sprites. Best-case is to draw all the particles to a canvas and create a base texture from it (`new PIXI.BaseTexture(canvas)`) then use that base texture to create each particle texture (one for each color/shape/etc `new PIXI.Texture(baseTexture)`). Then create one sprite per particle, and since they share a base texture they will be batched up.
