### ISSUE TITLE
Perhaps WebGL could be used for fast matrix calculations

### ISSUE THREAD

**Issue by tobireif** [GoodBoyDigital/pixi.js#1483]
I don't know whether it's applicable:
 Perhaps WebGL could be used for fast matrix calculations in pixi.js/src/pixi/geom/Matrix.js .

See
https://encrypted.google.com/webhp?hl=en#hl=en&q=webgl+matrix+calculations
http://stepheneb.github.io/webgl-matrix-benchmarks/matrix_benchmark.html
etc
(This lib seems fast: https://github.com/toji/gl-matrix )

**Comment by englercj** [comment]
I'm confused what you mean by "WebGL could be used for fast matrix calculations"? Do you mean do the calculations on the GPU? Because `ParticleContainer` does do that. Toji's gl-matrix doesn't "use WebGL" for the matrix implementation, it is just arrays so I'm not sure what you are asking for. Also, we used to use gl-matrix, but found that objects performed better the way we were using them, so we switched.

**Comment by tobireif** [comment]
Oh, you're right, toji/gl-matrix  doesn't use WebGL, I got that wrong.

> do the calculations on the GPU
> ParticleContainer does do that

Great! I thought it might be possible to also do that in pixi.js/src/pixi/geom/Matrix.js , but I don't know whether that is feasible.

**Comment by englercj** [comment]
@tobireif No, not really. It doesn't really work that way.
