### ISSUE TITLE
Spine bones being misplaced

### ISSUE THREAD

**Issue by oarmstrong** [GoodBoyDigital/pixi.js#1539]
```
Spine version 2.1.18
Pixi Version 2.2.7 and 2.2.8
```

I'm seeing a similar issue to #1468.  Bones appear to be misplaced, although unlike #1468 this doesn't just occur for animations with a draw order keyframe but for all animations.

You can see from [this image](http://1.1.1.4/bmi/s1.postimg.org/siwk1n51r/2015_03_15_193018_131x293_scrot.png) that the head and tie are too low, the arms are too close in and the lower leg (below knee) is too high up.  I don't know anything about Spine (I was given the files from my animator), so excuse any incorrect terminology, but it appears that the offset for the bones are using a flipped axis.  I've attempted `man.skeleton.flipX = true` and the Y axis counterpart but neither of those solved this issue, but did have a noticeable effect.  Everything works correctly in Spine and their skeleton viewer for the exported files.

Code used to create the animation:
```javascript
var man = new PIXI.Spine('anims/man.anim');
man.skeleton.setSkinByName('Skin Name');
man.skeleton.setSlotsToSetupPose();
man.position.x = window.innerWidth / 2;
man.position.y = window.innerHeight - 200;
man.scale.x = man.scale.y = window.innerWidth / 1200;
man.state.setAnimationByName(0, 'dancing', true);
this.stage.addChild(man);
```

Unfortunately I'm not in a position where I can share the `.spine` file or any of the assets, but I would be happy to provide screenshots of anything that may help.

/cc @mreinstein

**Comment by oarmstrong** [comment]
I've taken a [screenshot](http://s9.postimg.org/b9mhy53jz/2015_03_16_132852_280x646_scrot.png) of the man from spine.  I've been asked to obscure the face, for some reason the PM is a little careful about putting anything on the internet which could expose the project.

**Comment by mreinstein** [comment]
instead of `setSlotsToSetupPose()` try `setToSetupPose()` and see if that fixes it for you.

**Comment by mreinstein** [comment]
I've found this document to be incredibly useful on some occasions: http://esotericsoftware.com/spine-using-runtimes

**Comment by oarmstrong** [comment]
Thanks for the suggestion, but no luck there.  This exact code works fine for the sample spine animations that are found in examples (sans the set skin line which isn't needed for those), so there's an *issue* with my Spine project.  Either the way its exported or the way its actually created.  But I'm hoping that those animation don't have to be re-exported or even completely remade, and that a line or two of JS will solve the problem.

If there are any pointers about the specifics of where in the Pixi file I should investigate then I'll take a look at that.  I'm not fully sure whether this is the bones, slots, attachments or something else which is being incorrectly placed.

**Comment by mreinstein** [comment]
> so there's an issue with my Spine project

yeah one thing I noticed about your bones (which I didn't mention because you said it animated fine in the spine editor) is that they dont seem to have a traditional hierarchy. Looking at your image. It seems that the upper leg and lower leg bones descend from the knee joint. this is atypical I think. Notice that in my example, the lower leg bone is a child of upper leg, and upper leg is a child of the hip.

![screen shot 2015-03-16 at 12 40 34 pm](https://cloud.githubusercontent.com/assets/718067/6674856/cb8e59d4-cbd9-11e4-92b0-ccf5ffbd0034.png)

**Comment by oarmstrong** [comment]
Thanks, if you don't mind I'll quote that to the animator and see if I can get something done about it.

I'll keep this open as it may still be a bug with Pixi if it cannot manage this hierarchy?  I appreciate what I've got is probably incorrect, but an error message or some documentation on this would be sweet if it cannot be resolved.

**Comment by mreinstein** [comment]
> it may still be a bug with Pixi if it cannot manage this hierarchy?

It's really hard to say what the problem is with the given information. without the assets or a video or more info I can't really say what the issue is. I suspect it is with your animation structure but can't be sure.


> but an error message or some documentation on this would be sweet if it cannot be resolved

It's not clear to me what the problem is though. So I'm not sure what error message would be displayed. are you saying something like "detect when a non-humanoid skeleton is used and alert the user" ? Humanoids are one type of an infinite variety of animations that you could produce with spine, everything from dragons to turrets to powerups to more exotic things I can't even think of.

**Comment by oarmstrong** [comment]
> Humanoids are one type of an infinite variety of animations that you could produce with spine, everything from dragons to turrets to powerups to more exotic things I can't even think of.

That's true, however even if this was a non-humanoid skeleton, surely this is still an issue?  I would expect everything to still be in the correct placement if this were a turret or any other object.  Am I missing something?

I appreciate your help and I understand it's difficult when I'm not able to share my assets with you.

**Comment by oarmstrong** [comment]
I've managed to learn enough about Spine myself to create a quick stickman test animation and that works with no issues.  I'll get my animator to view what I created and to amend his hierarchy to match.

Nonetheless, it's still odd that my original animation viewed fine in Spine and the [Skeleton Viewer](http://esotericsoftware.com/spine-skeleton-viewer) but not Pixi.  To me this seems like a bug, but I could easily be wrong.

**Comment by mreinstein** [comment]
> To me this seems like a bug, but I could easily be wrong.

It may be, but it's not actionable in terms of a fix. I'd recommend closing the issue, and re-open if it turns out to be something specific. Just my 2 cents.

good luck!

**Comment by oarmstrong** [comment]
Thanks for all your help!

Without sounding offensive, but are you actually a contributor to Pixi?  I couldn't see anything on your profile page about it.  If not, then I'll keep this open for a dev to take a peek at and they are more than welcome to close it off if this is not specific enough or is not an issue.

**Comment by mreinstein** [comment]
> Without sounding offensive, but are you actually a contributor to Pixi?

It's definitely not offensive. :) No, I'm not a contributor, I'm a new user to it like you. I have a desire to contribute though, and one way to do that is to help with easing the support burden (trying to answer github issues, etc.)

> If not, then I'll keep this open for a dev to take a peek at

You're certainly welcome to do that. I don't mean to imply any authority in telling you my thoughts on the problem. I *suspect* that this particular issue as it is currently described is not very actionable, and hard to solve. but that's just my gut feeling. My hope was that I could help you with this issue myself and save them a few cycles since they are very busy releasing v3 stuff.

**Comment by oarmstrong** [comment]
You're awesome.  People like you really help the community.

I'll close this off to keep the burden low on the devs.  With any luck they'll still see it and reopen if it is an actionable bug.  There is a workaround so it's a minor issue at best, especially as nobody else seems to have this issue

Thanks again, and I wish you the best with everything.
