### ISSUE TITLE
[V3-RC2] webGL Renderer crash in CocoonJS 

### ISSUE THREAD

**Issue by Greewi** [GoodBoyDigital/pixi.js#1555]
Hello,

We discovered that the CocoonJS does not implements gl.getContextAttributes(). In Cocoon this method seem to only returns undefined. This method is used in the initialization if the webGL renderer (antializing setting) and the auto detection of the renderer (stencil availability check).

Because of this, we can't initialize the webGL renderer (or use the auto detect renderer feature, but we need the webGL renderer anyway).

**Comment by englercj** [comment]
Damn you CocoonJS! Any chance of them fixing this issue on their end, if not I guess I can hack around it...

**Comment by JiDW** [comment]
getContextAttributes is listed as a supported feature here : http://support.ludei.com/hc/en-us/articles/200807787-HTML5-feature-list

So they may want to fix it on their side. We'll fill a bug report with Greewi and report the result here.

**Comment by mattdesl** [comment]
Regarding the need for this function...

The FXAA stuff seems a little bit "magical" and could lead to headaches. Unless I'm mistaken; it looks like it gets enabled when antialiasing is requested but not detected. It seems to [override the filters](https://github.com/GoodBoyDigital/pixi.js/blob/f73a72a928f5cf9833d6c783c78cdeb8ac8fc831/src/core/renderers/webgl/WebGLRenderer.js#L231) of rendered objects and introduces an extra render pass under the hood which the user wouldn't otherwise expect. It could definitely cause quirks when the user is expecting pixels to be rendered normally, like situations where a [color lookup table](https://www.npmjs.com/package/glsl-lut) is used, or when rendering pixel-perfect sprites or bitmap fonts.

IMHO it would be better to have the user decide when and how to enable FXAA, and let them decide how to detect `antialias` themselves. In my own projects I prefer an [optimized version](https://github.com/mattdesl/glsl-fxaa) which leads to less dependent texture reads. Other projects may need something tailored to the application itself.

The other area this function is used is in `isWebGLSupported`. Again I think it's best to take the easy road and avoid the "magic," just do a simple check. 

Maybe warnings could be logged for problems like these:

```{ 
  stencil: true, 
  antialias: true, 
  failIfMajorPerformanceCaveat: true 
}```
(see [here](http://blog.tojicode.com/2013/12/failifmajorperformancecaveat-with-great.html))

**Comment by englercj** [comment]
Closing this issue as the crash seems to be on cocoon's side
