### ISSUE TITLE
Something goes (horribly) wrong in CocoonJS when you render with webgl

### ISSUE THREAD

**Issue by JiDW** [GoodBoyDigital/pixi.js#1562]
Hello,

There is a strange bug with PIXI v3 and CocoonJS and it is very hard to understand what.
To understand why our game didnt work with PIXI v3 and CocoonJS, we created an empty canvas/container and tried to add texts, sprites and graphics to it and see what happens.

Under some combinations of displayobject, the renderer fails silently and nothing is displayed.

I will use symbols to represent our test cases : T is for a PIXI.Text, S is for a PIXI.Sprite and G is for a PIXI.Graphics.

The order of the combination is revelant.

T :ok: 
S :ok: 

TT :red_circle: 
TS :ok:
ST :red_circle: 
SS :ok: 

TTT :red_circle: 
TTS :red_circle: 
TSS :ok: 
SSS :ok: 
STS :red_circle: 
SST :red_circle: 
STT :red_circle: 
TST :red_circle: 

So it appears that you can't have more than one Text, and it can only be in first position in the container.

But, because there is magic in this world, everything works again when you add one or more graphics.
It can be at any position, it fixes every combination we tested.

Do you have any clue of why this happens ? We really need to debug this as we need to use PIXI v3. We could really use advices or ideas to pinpoint the bug.

**Comment by englercj** [comment]
Wow that is some strange behavior, @GoodBoyDigital any ideas off the top of your head before I dig into this?

**Comment by JiDW** [comment]
We have some untested idea about shaders setter. I believe that PIXI.graphics use a different shader than sprite, could it be that PIXI.Text does not clear/set/get a shader in the correct way ? 

I would still expect PIXI to draw at least some of the "STS" combination if it was the case, so shaders may not be related.

**Comment by GoodBoyDigital** [comment]
interesting stuff! Is there anyway to debug this kind of stuff? does cocoonJS output any info at all?

**Comment by JiDW** [comment]
Yes, you can use console.log with the CocoonJS Launcher or use Android monitor and XCode output window to see these logs.

As this bug happens in the CocoonJSLauncher too, there's no need to compile an APK, just put your files on your phone and launch index.html in Canvas+

**Comment by mattdesl** [comment]
Can you provide the smallest amount of code to reproduce the bug, and also detail what versions of the CocoonJS Launcher and what device you are testing on? 

It's probably something related to GL state -- maybe a uniform is not getting set, or something is not being bound, etc. It could be that desktop has a better guard against undefined values whereas CocoonJS just craps the bed.

I've noticed some other small bugs with CocoonJS:

- `gl.drawingBufferWidth` / `gl.drawingBufferHeight` was missing
- `canvas.toDataURL` is not spec compliant when ScreenCanvas is enabled
- `uint32` indices work on desktop but break on CocoonJS; had to switch them all to `uint16`

**Comment by JiDW** [comment]
Yes, here it is : http://www.celsius-heroes.com/testPIXIV3/testPIXIV3.zip

You can comment/move lines in test.js to test multiple case.

We're testing with the last version of cocoonjs (2.1.1) on Android 5.0 (Nexus 4). I'll have to check but I'm nearly sure we tested on Android 4.4 too.

**Comment by mattdesl** [comment]
I uncommented all the lines and tested on an iPhone 5s, iOS 8.1.2, with CocoonJS Launcher 2.1.1.2. I had to remove the `resolution` parameter to be able to see any of the content (it seems bugged?), but after that I was able to see all the display objects as expected.

Maybe it is specific to Android?

**Comment by JiDW** [comment]
If you uncomment all the line, you uncommented the Graphic object. As stated, putting a Graphic object fix the issue.

Try to put only 2 or 3 texts.

**Comment by GoodBoyDigital** [comment]
hey all! Whats the status of this one at the mo?

**Comment by JiDW** [comment]
Hello,

This bug is still in effect with the RC4.

I'm losing my head trying to understand it.

At this moment, I'm 80% sure that is it highly related to PIXI.Text.updateText()

If you have an idea or can help with this one, that would be awesome ! We're going to show it to Apple and Google in the following weeks and we really need a stable version :/

**Comment by JiDW** [comment]
Btw, I'm talking about updateText() because if you draw two sprites, wait 2 seconds, and then draw a text, you will see the two sprites during the two seconds before the drawing of the text, then nothing.

**Comment by JiDW** [comment]
My latest results are, in my opinion, the most interesting in order to debug this.

1- Put two sprites => it works
2- Wait 2 seconds
3- Put a text => It produce a black screen
4- Wait 2 seconds
5- Put a Graphics => it works again
6- Wait 2 secondes
7- Put a second text => It works

So There's something that the render of a Graphics does that is not done for a sprite or a text.
And there's something that is done when a text is rendered that is not done with a sprite (canvas texture maybe ?)

**Comment by englercj** [comment]
Just to confirm, does this issue happen with the latest v3 release?

**Comment by JiDW** [comment]
Yes it does.

I found that this bug is affected by the way CocoonJS create a canvas and a "screencanvas" 

http://support.ludei.com/hc/en-us/articles/201810268-ScreenCanvas

The correct way to handle this property should be to use "disabled by default" and to set it to true on the "stage" canvas.

But it produces even more incoherent behaviors.

**Comment by JiDW** [comment]
I've contacted Ludei in the hope to get some help. I'm sorry for being a bit pushy on this issue but having our main project with a major incompatibility on our main platform is giving me a cold sweat !

http://support.ludei.com/hc/communities/public/questions/202273039-Incompatibility-between-CocoonJS-webgl-and-PIXI-v3

**Comment by MortimerGoro** [comment]
Hi,

I have been debugging this issue and finally fixed it.For performance reasons Cocoon uses the same OpenGL context for all WebGL and Canvas2d context operations. When a text is rendered in a normal 2d canvas, Cocoon uses vertexAttribPointer to set up it's own shader. The problem was that the new attrib pointers were crushing the attrib pointers that PIXI had set in previous operations assuming that they would remain cached. With the new fix Cocoon stores and restores vertexAttribPointer data to avoid these kind of conflicts. This changes fixes this issue (tested on iOS and Android) and might help to fix others too ;)

The fix is already deployed to the 2.1.1 branch in the cloud compiler. We'll upload a new CocoonJS Launcher to the markets. Meanwhile, you can generate you custom launchers in the cloud or compile the games.

**Comment by JiDW** [comment]
Amazing !! Thanks a lot Imanol ! I'm testing it and will close the issue when I'm done :)

**Comment by JiDW** [comment]
It's perfect ! :) Thanks again to Imanol and everyone who took a look at it !

**Comment by Havaris** [comment]
Hi everybody!
Since v3 cocoon is horrible and drives me crazy.
Bref, I don't understand @JiDW, because custom luncher or not, your TESTPixiV3 folder just display graph.
I comment lines, uncomment lines, and with the blue background, I only have graphs. No sprite, no text. If I put 1 only sprite it's the same, it show nothing.

Your setTimeouts display a black square who correspond to the sprite "display", but after the black square, nothing.

In fact, V3 with cocoon in WebGL mode don't show sprites.
The auto detect renderer put cocoon in canvas mode with V3. The problem start here because my project was at 60 fps in V2 to 20-30 fps in V3 and I didn't understand why before I realize cocoon put me in canvas mode).

I test that with android.
I tested compiled projet, custom and basic luncher.

I don't understand what is fixed with the fix in fact.

Is your test folder work for you since the fix?

I love Pixi and Cocoon but love drive crazy.
