### ISSUE TITLE
[V3] Loader: middlewares don't use the loader options

### ISSUE THREAD

**Issue by ayamflow** [GoodBoyDigital/pixi.js#1663]
So I'm loading a spritesheet with a `PIXI.Loader`, and passing some options to it.
The spritesheetParser middleware recognizes that as a spritesheet and adds the associated `.png` to the loader queue. Thing is, the spritesheetParser is passing its own options hash.

It causes an issue since we are working on a server that doesn't allow `loadType: Resource.LOAD_TYPE.IMAGE` (the option that the middleware uses).

Not a big deal, will monkeypatch, but not easily overridable (need to hack into node_modules).

+ @englercj

**Comment by englercj** [comment]
> at doesn't allow `loadType: Resource.LOAD_TYPE.IMAGE`

Not sure what you mean, the server doesn't really know the difference between an image or xhr request, they look the same? What is the issue you are encountering?

**Comment by ayamflow** [comment]
Yeah it was related to [this one](https://github.com/englercj/resource-loader/issues/8).
By "doesn't allow" I made a shortcut but basically the page is password protected and I'm not sure we can put the password into the URL (we are deploying to different targets, some with password some without and don't want that in clear.

Do you think it makes sense that the spritesheetParser should fallback on the loader configuration? Or is it something to manage differently on my end.

**Comment by englercj** [comment]
If you are doing basic auth the password is unencrypted over the wire whether you pass it in the url or not. I can look into trying base loader config instead of what it passes in, but it gets complicated because the parser *knows* it wants an image, and passing IMAGE is faster and more compatible that using XHR and blob parsing.

Honestly the *best* solution is for you to handle auth (if it is just basic auth) in the url, or cookies (if session auth). Either way, the load method doesn't matter so it all just works.

**Comment by ayamflow** [comment]
Thanks! Honestly, I think I will just keep copy pasting my config in the spritesheetParser file since it's just the testing server. But isn't kind of unexpected behavior to be allowed to pass options and they get overwritten by a piece of code that you can't control?

**Comment by englercj** [comment]
@ayamflow But you don't pass options for the resources that the parser decides it needs to load. You pass options for that resource itself (via .add). You passed in that it should load the json via XHR, but you can't pass in how it should interpret that json and load sub data. 99% of the time you want the parser to decide for you, because it knows what it needs.

This is the only case where you might want to change it, and honestly I'm not convinced that introducing complexity the parsers have to be aware of is the way to go. Especially when there is a best practice to do it with current tech already. If you build a PR we can review and merge it, but I don't think I will be adding sub-resource option passing anytime soon without a more compelling use-case.

**Comment by ayamflow** [comment]
Hm yeah it makes sense. :+1:

**Comment by englercj** [comment]
Thanks for being so understanding :smile:
