### ISSUE TITLE
[All Versions] Performance issue when combining combining text and graphics within the same container

### ISSUE THREAD

**Issue by shinybob** [GoodBoyDigital/pixi.js#1666]
When adding a Graphic and Text object to the same container performance is MASSIVELY effected.

Testing on an iPad Mini I'm able to get only 60 elements when combining in the same container but 1200 when placing in separate containers. There also seems to be an issue if the Text and Graphics are different containers but share a parent but I didn't have time to make a test for this.

The issue only appears to happen when using WebGL. I've also tested on a selection of iOS and Android devices and get similar results. It's not as noticeable on Desktop.

http://jsfiddle.net/shinybob/5486u6ps/32/

**Comment by shinybob** [comment]
I have also tested against the latest RC and the issue is still present.

**Comment by GoodBoyDigital** [comment]
This is due to the way pixi renders stuff. in the second slower example you are forcing pixi to switch render states as it draws text -> graphics -> text -> graphics..

In the faster example pixi is batching the calls text -> text -> text -> text... graphics->graphics->graphics..

Pixi is at its fastest when it can batch sprites. It can achieve this when elements that are next to each other in a container are the same type of object. Further optimisation can be found by using spriteSheets and making multiple objects use the same texture.

Hope this helps! thanks!

**Comment by shinybob** [comment]
Just thought I'd clarify that when I say Graphic I mean the PIXI.Graphic object and not a preloaded image or sprite sheet. If I load a image (individual texture or sprite sheet) I do not notice the issue.

I did find that by setting cacheAsBitmap to true on the graphics object it solves the performance issue. However, if the object is set to be interactive, the hit area behaves erratically, normally being reset to the top left of the screen. This issue appears in V2 but seems to be fixed in V3 so I didn't raise an issue.
