### ISSUE TITLE
[v3 RC4] Issue with bitmap font loading ?

### ISSUE THREAD

**Issue by alaa-eddine** [GoodBoyDigital/pixi.js#1701]
Hi, 
I don't know if this is a bug or misusage of the BitmapText in Pixi v3.

here is my code 

```javascript
PIXI.loader.add('./data/fonts/desyrel.fnt');
PIXI.loader.load(function () {
	console.log('loaded')
});
```

I see "loaded" output in the console.
but when I try to use the font using the following code

```javascript
var bitmapText = new PIXI.extras.BitmapText("text using a fancy font!", {font: "35px Desyrel", align: "right"});
```

I get an error in BitmapText.prototype.updateText complaining about empty font data.

and when I check the content of font cache, PIXI.extras.BitmapText.fonts is empty !

for information, font file raw data is present in PIXI.loader.resources

is this a bug ? or I'm doing something wrong ?

**Comment by englercj** [comment]
Sounds like a bug, do you have a running example I can debug on?

**Comment by alaa-eddine** [comment]
here is a live example http://labs.ezelia.com/pixi/bitmapfont/

font files are : http://labs.ezelia.com/pixi/bitmapfont/data/fonts/desyrel.fnt
and : http://labs.ezelia.com/pixi/bitmapfont/data/fonts/desyrel.png

I just noticed in the network tab that .fnt file is loaded but not the .png .... 
can this be the problem ? do it need to be explicitely added to the loader ?
it was not the case with Pixi 2 I think.

**Comment by englercj** [comment]
It does not need to be explicitly added, I'll take a look.

**Comment by englercj** [comment]
First thing I notice is that you are not on the latest pixi `dev` branch. First update to the latest. Make sure to clone the repo or update your version if you have it cloned, and ensure all dependencies have updated as well by running `npm install` from within the clone of pixi. Then run `gulp` to build a new version of pixi.

After you have the latest version of pixi, make sure your file gets loaded as XML (it isn't right now because the loader doesn't recognize '.fnt' as an XML file. To force a load type you can do:

```js
PIXI.loader.add('data/fonts/desyrel.fnt', { xhrType: PIXI.loaders.Loader.XHR_RESPONSE_TYPE.DOCUMENT });
```

Or you could change the extension to `.xml` and that would work as well. If you update pixi (and dependencies), use the new build, change your code as above, and it *still* doesn't work then just ping this thread with the updated example and I will look at it.

**Comment by alaa-eddine** [comment]
Thank you,

Tried with the latest build, and it's working with .xml files

there is just something that was wrong in your example PIXI.loaders.**Loader**.XHR_RESPONSE_TYPE is undefined

I used PIXI.loaders.**Resource**.XHR_RESPONSE_TYPE.DOCUMENT instead

**Comment by englercj** [comment]
Sorry, typo! Glad it is working now, feel free to put in an issue/PR for resource-loader if you want it to natively support `.fnt` files.
