### ISSUE TITLE
How to use spine with Pixi v3+  ????

### ISSUE THREAD

**Issue by zhkuang** [GoodBoyDigital/pixi.js#1711]
How to use spine with Pixi v3+  ????

**Comment by JiDW** [comment]
PIXI.spine is now a plugin : 

https://github.com/pixijs/pixi-spine

**Comment by cinkonaap** [comment]
Examples of Spine aren't working, like here: [Gobling Example](http://pixijs.github.io/examples/index.html?s=spine&f=goblins.js&title=Goblin)

I am trying to use the plugin with Dragon from Spine Trial, but I gets 
`Uncaught TypeError: Cannot read property 'skeleton' of undefined @ Slot.js:35`

**Comment by zhkuang** [comment]
I have the same problem！！

**Comment by cinkonaap** [comment]
Ok so the problem is:

`var bone = this.bones[skeletonData.bones.indexOf(slotData.boneData)];` @ `Skeleton.js:23'

because this.bones is an integer indexed array, but slotData.boneData is type of string (for dictionary), so undefined is passed to Slot and bg happens

**Comment by englercj** [comment]
Pixi examples with spine weren't working because the plugin wasn't present:

https://github.com/pixijs/examples/pull/5

Now it is there we are trying to work through some issues with how plugins integrate:

https://github.com/pixijs/examples/issues/4
https://github.com/GoodBoyDigital/pixi.js/issues/1713

etc. Please be patient while we work through the issues. If you have problems using pixi-spine, please post issues on their repo. Pixi.js no longer ships with spine support, it is all in that plugin now.
