### ISSUE TITLE
currentFrame

### ISSUE THREAD

**Issue by berezmax** [GoodBoyDigital/pixi.js#1719]
error currentFrame
line 18573 - this._texture.length => change this._textures.length

**Comment by englercj** [comment]
Please try not to open vague issues like this with no context, it makes it hard to find exactly what you are talking about.

I *think* you *might* be talking about something that was fixed by #1704, but I have no idea because "line 18573" doesn't point to any line that does that for any of our compiled builds.

It is much more helpful to say which build you are using, which version it was, and show in your debugger what the error was.

**Comment by berezmax** [comment]
I assume that the error in version 3.0.0
currentFrame = NaN
If you change to this._textures.length no error

ps. Ssory my english

**Comment by englercj** [comment]
We already changed it, it will go out with v3.0.2

https://github.com/GoodBoyDigital/pixi.js/blob/dev/src/extras/MovieClip.js#L126

**Comment by berezmax** [comment]
Thank you! You best!
