### ISSUE TITLE
Container width/height affecting scale

### ISSUE THREAD

**Issue by bmantuano** [GoodBoyDigital/pixi.js#1794]
Hi guys, I see this one is intentional given the comments here:
https://github.com/GoodBoyDigital/pixi.js/blob/master/src/core/display/Container.js#L38

I'm wondering what the prescribed method is in terms of applying a size to a container without it actually scaling.  

A tab bar is an example of where this would be useful - where a consumer would want to size the overall tab bar and then let the tab bar intelligently size its children to fit within the total space.

We could override these setters/getters in a subclass, but it gets tricky given Container is a such a low-level class and that other low-level classes (Graphics, Sprite, etc.) extend from it.  

Could we add an option to toggle this behavior?  Or is there a better way to get the behavior I'm looking for?

Thanks!

**Comment by englercj** [comment]
You are correct in that it is on purpose that we scale when the user sets the width/height. What else would it do? For all cases setting the width means "I want it to be this big" and scaling is the only thing we can do to make that happen.

For the specific case you mention it sounds like you want to have layout properties and methods, but are trying to reuse the width/height to achieve it. Honestly what you are describing all sounds like new functionality that a subclass would implement (think maxWidth or flexWidth or layoutWidth). But it doesn't necessarily describe the *render* width of the object, if it does then we have to scale the object to reach that width :)

Hopefully that makes sense?

**Comment by bmantuano** [comment]
Hi @englercj, thanks for getting back on this.  I think I'm looking at it in a more generic way than just pure rendering and as you say, getting into layout.  

I'm seeing width/height as a standard interface that's used to size components.  The implementation of width/height needs to be different of course across components (e.g. Charts, Tabs, Dialogs, Lists, ScrollViews, Maps, etc.), but using the single width/height interface keeps things simple for the higher levels (e.g. CollectionView that needs to handle heterogenous content).  

Scaling works great for certain things like assets, but I'm not sure it's a good default for most containers.  Anyhow, perhaps outside the scope Pixi is aiming for, but something to consider.  We'll be able to subclass to get the behavior we're looking for with a little effort.  Thanks again.

**Comment by englercj** [comment]
> Scaling works great for certain things like assets, but I'm not sure it's a good default for most containers. 

That statement is probably quite true, a general container probably shouldn't scale for width/height changes. I think that also may be outside the scope of the core library since it is a rendering library, everything we do in here has to do with rendering.

If you run into any trouble with getting a layout manager going, let me know. I'd like to see an open source one crop up soon :)

**Comment by msqaddura** [comment]
Sorry to come here after a long time.
Indeed your container will scale when you change width/height as so
```
    set width(value) // eslint-disable-line require-jsdoc
    {
        const width = this.getLocalBounds().width;
```
I had the very same issue few days ago while trying to use **Autolayout.js** with PIXI and the solution is pretty simple. 
say you have a scene, that has a container that has a sprite like this
-Scene
--Container (half size of Scene and center-aligned)
---Sprite(half size of Container and center-aligned)


if scene is {x:0,y:0,width:200, height:200}
then Contianer will be {x:50,y:50,width100,height:100} |50->Container(100)->50|
hence Sprite will be {x:25,y:25,width:50,height:50}  |25->Container(50)->25|

now when the screen resizes, or you just want to resize  you basically do
1) apply x,y for containers and dont apply width and height
that means that the _CONTAINERS will ONLY MOVE..._ 
2) pass the width and height of the Container to the Sprite so that it knows how much  _SPRITE should RESIZE AND MOVE_ and apply width,height,x,y based on its parent 
3) although you did not change the width and height of container... you passsed them to the sprite... the sprite causes the actual width and height (localBounds) to be changed back.
