### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by nozhdelov** [GoodBoyDigital/pixi.js#1824]
Hi guys,

I have an app with renders one huge tailing sprite for background and a few thousand sprites on top of it.
The scene is static most of the time but even then my CPU and cooling fan are going wild. I noticed that for every rendering of the stage (the top most container) the JS heap size grows almost 3 times and then  there is a forced GC immediately after that.  I am attaching a screenshot of my chrome timeline.
Any thoughts?

![screen](https://cloud.githubusercontent.com/assets/1628329/7696093/2a46632c-fe02-11e4-9049-4ae378762e05.png)

**Comment by drkibitz** [comment]
If there is a sawtooth pattern it's not a leak, you would see it stair step if it was. What it does sound like is massive object allocations, most likely unnecessary. Would be great to put

**Comment by drkibitz** [comment]
Sorry trying new git app 😕 ...
To put the reduced case in a jsfiddle as I'm sure everyone would be interested in the cause and to fix this issue.

**Comment by nozhdelov** [comment]
Hi ,

Thanks for the reply. 
I made a simplified version here https://jsfiddle.net/ggdyuvL8/3/ 
As you can see the amount of memory increases with every frame until the GC kicks in

**Comment by jwdunn1** [comment]
I'm not detecting a memory leak, however, I've seen allocation/GC behavior on most rAF-based (requestAnimationFrame) engines. It's more pronounced on high frame rate monitors, since a 144Hz monitor runs the rAF loop more often. The trick, I've found, is to intelligently manage the need to run the loop and, possibly, to throttle the rAF loop to save on CPU cycles. As you state, your scene is static most of the time, so the only time the loop needs to run is when something changes. For example,  trigger the render loop only when UI events occur or when an animation is launched. After the animation is complete, the system can go back to idle. At idle, there are zero events logged to the Chrome timeline.

You will also note in your inspection, there are two rAF events. One is internal to Pixi which can turned off by adding this: var ticker = PIXI.ticker.shared; ticker.autoStart = false; ticker.stop();

For rAF throttling, see: http://codetheory.in/controlling-the-frame-rate-with-requestanimationframe

Functions like loop() and noLoop() in Processing, can be implemented to better control model update and screen rendering cycles.

**Comment by englercj** [comment]
Hey @nozhdelov, thanks for bringing this up. Like @drkibitz mentioned this pattern is not indicitive of a memory leak but instead of excessive garbage allocation (short-lived objects).

This is actually a pretty healthy graph. An empty RAF loop will cause a sawtooth pattern in itself, so that is part of it. The larger part that is causing this sawtooth is that we allocate some temporary objects in the sprite canvas render method:

https://github.com/GoodBoyDigital/pixi.js/blob/master/src/core/sprites/Sprite.js#L388-L393

These objects are created, used, then immediately destroyed. Contributing the most to the allocations each frame:

![image](https://cloud.githubusercontent.com/assets/944497/7705632/44a5a758-fdfa-11e4-95c0-dfe355bb7a49.png)

Notice that there are 0 but 101, 505 allocated objects from the `Sprite._renderCanvas` method. This is a speed-memory tradeoff. By caching those objects in the method we can greatly increase the speed of accessing them, at the cost of a bit of memory churn. Unless you are seeing serious issues due to GC I wouldn't worry about this.

**Comment by nozhdelov** [comment]
Thanks a lot for the answers :) 
I can't really stop the render loop because I also have a few MovieClips running but I will try some of the other techniques you mentioned. I guess I don't really need 60 FPS all the time.

**Comment by drkibitz** [comment]
You could try to render using the shared ticker

**Comment by drkibitz** [comment]
@nozhdelov to elaborate on my last comment. When using the ticker, it already gives you a `deltaTime` value, where the value of `1` equates to the target frame rate, (e.g. a tick 60 fps). A ticker still "ticks" at the platform's refresh rate, but in the case a tick was faster than the target frame rate, it should give you a deltaTime of `< 1`. Basically, you can use this value as your clamp if you wish, otherwise you will probably end up implementing something similar.

At some point during a refactor, I considered clamping this as part of the ticker (something similar to MovieClip), but I thought this was too much, as the consumer can already decide whether to render at the refresh rate or the target fps using the delta, and the target frame rate constant is configurable at `PIXI.TARGET_FPMS`. More opinions on this are welcome.

**Comment by nozhdelov** [comment]
@drkibitz sorry for the late reply. I didn't notice your last comment then. Actually  I did exactly what you described a few weeks ago and it worked great :) . Thanks again for the help
