### ISSUE TITLE
sorting inside graphics class

### ISSUE THREAD

**Issue by andrevenancio** [GoodBoyDigital/pixi.js#1876]
If a sprite is added to a graphics objects through the addChild mode, the sprite always stays on top of anything being drawn on it.

```
var graphics = new PIXI.Graphics();
something.addChild(graphics);

var sprite = PIXI.Sprite.fromImage('someimage.png');
graphics.addChild(sprite);

graphics.clear();

graphics.beginFill(0xff00ff);
graphics.drawRect(0, 0, 200, 200);
```

This should either clear everything on the graphics (including the image) or
draw the elements on top of whatever's there.

Opinions?

**Comment by englercj** [comment]
The way objects are drawn is by drawing the object then its children. An object's children will always be on top of an object.

If you want it below the graphics make it a sibling in a container.

**Comment by andrevenancio** [comment]
I understand that.. maybe I should have been more explicit.. I think the drawImage method in the graphics is missing. :) There might be the case where your "graphic" object is complex enough to have an image and some lines on top of the image.. or whatever :)

**Comment by englercj** [comment]
http://www.html5gamedevs.com/topic/15045-drawing-images-onto-a-pixigraphics-obj/?p=85355

I don't think that graphics should draw images, I think that is adding complexity to an already complex object in order to make it do something it was never meant to. You can easily solve this problem using the existing objects and methods in pixi.js
