### ISSUE TITLE
WebGL contexts

### ISSUE THREAD

**Issue by jwdunn1** [GoodBoyDigital/pixi.js#1923]
This is probably related to some older context issues (like #460), but I am attempting to completely tear down a pixi WebGL context. Either I am missing a step, or there is something still allocated deeper in the object chain. In this fiddle (http://jsfiddle.net/intrinsica/sfzmmvvm), clicking on the stage will deallocate and reinitialize.

On Chrome, using the autoDetectRenderer method, after about 8 clicks, a message appears in the console: "pixi.js:12442 WARNING: Too many active WebGL contexts. Oldest context will be lost." In Firefox, the warning is: "Error: WebGL: Exceeded 16 live WebGL contexts for this principal, losing the least recently used one."

If the WebGLRenderer method is used, it takes about 16 iterations to get the warning.
The warning does not appear with the canvas renderer. Ideally, WebGL should behave too.

**Comment by englercj** [comment]
> The warning does not appear with the canvas renderer.

Because there is no canvas 2d context limit (AFAIK), but there is one to webgl and they are *garbage collected*. We don't control when we contexts go away, the browser does. It is possible that we are holding references that keep it alive so it can't GC, and that is causing the logs? But I would propose that the logs you are getting are not a "problem" for your application. It is just Chrome telling you it is recycling old contexts.

**Comment by jwdunn1** [comment]
Thanks for the feedback. A stress test running 5000 iterations of WebGL renderer buildup/teardown indicate memory usage is flatline, so I'll ignore the console warnings.
