### ISSUE TITLE
Opposite of Masking?

### ISSUE THREAD

**Issue by Squeakrats** [GoodBoyDigital/pixi.js#252]
is there anyway to instead of showing whats in the mask, hide it?Thanks!
(btw Pixi is really awesome!)

**Comment by GoodBoyDigital** [comment]
closing this for now. We won't be making inverted masks - but this is entirely possible with the new spriteMasking in v3. Thanks all!

**Comment by jdoleary** [comment]
Is this now complete in v3.x?  How would inverted masks be used?

**Comment by englercj** [comment]
Like @GoodBoyDigital said, we will not be making inverted vector masks, but you can accomplish it with sprite masking.

Since you can use an image for masking, you can do anything. Including having a sprite that uses a canvas as a texture and drawing whatever you want to it.

**Comment by jdoleary** [comment]
My mistake, I thought since it was added to the v3.x milestone that it would be added.

I still don't understand how I could use a sprite to invert a mask.  I'd still have the same problems wouldn't I?  I want to draw a series of polygons to a sprite, invert them, and use that as a mask.  I don't see how that is possible.

**Comment by englercj** [comment]
alpha masks use alpha / color, so black and alpha of 0 will mask the item. You can draw black/alpha 0 wherever you want in an image, then apply that mask. #1639.

So you can draw a polygon where it is filled with white, and all the other transparent areas that are not drawn will be the masks, or you can do the reverse. Whatever you draw is the mask.

**Comment by Squeakrats** [comment]
Awesome to see this is working! That makes sense.

**Comment by Saltallica** [comment]
I now this is closed, but I figured I'd throw another opinion in the mix, since I would find it practical to be able to have a mask similar to canvas "destination-out" compositing.  

In the game I'm building, I want to "punch a hole" in a blimp. The way I currently have it set up, I dynamically create a white, rectangular mask, with a few black polygons to represent the holes.
I save to a texture, then a sprite, then set it as the mask to the blimp sprite.  This gives the illusion that the blimp sprite has holes in it. This works, for simple static masking.

Some visuals - A blimp, and a mask with the same bounds and a few holes.

![image](https://cloud.githubusercontent.com/assets/1064853/18255507/5dbf3e80-7378-11e6-9d34-41be630dadb6.png)


If I want to "fade in" the holes over an amount of time, I thought maybe I could just adjust animate the alpha value of the mask - this didn't end up with the expected result, as the white and black are required for the mask to behave "correctly." When animated, the whole blimp fades in, not just the wholes.

Ideally, I would like to simply have a mostly transparent sprite with a few areas that are completely white. These would then get set up as mask and subtract the alpha of the container/sprite it's assigned to. A destination-out style blend mode would accomplish this.
